---
title: "Meningioma Dose Response Summary"
author: "Robert Allaway, Abhishek Pratap"
date: "5/16/2017"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
tables: true
geometry: landscape
header-includes: 
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library("synapseClient")
library("nplr")
library("plyr")
library("dplyr")
library("data.table")
library("plotly")
library("reshape2")
library("ggplot2")
library("foreach")
library("tables")
synapseLogin()
booktabs()
```

```{r, include=FALSE}

get_drugResponse_stats <- function(conc,viability,...){
  res <- nplr(conc, viability,...)
  results <- getAUC(res)
  results['goodNess_of_fit'] <- getGoodness(res)[1]
  results['stdErr'] <- getStdErr(res)[1]
  ICx_est = getEstimates(res, targets=
c(.10,.20,.30,.40,.50,.60,.70,.80,.90), conf.level = 0.95)
  results['IC10'] = ICx_est[1,'x']
  results['IC20'] = ICx_est[2,'x']
  results['IC30'] = ICx_est[3,'x']
  results['IC40'] = ICx_est[4,'x']
  results['IC50'] = ICx_est[5,'x']
  results['IC60'] = ICx_est[6,'x']
  results['IC70'] = ICx_est[7,'x']
  results['IC80'] = ICx_est[8,'x']
  results['IC90'] = ICx_est[9,'x']
  results['IG50.CI.lower'] = ICx_est[5,'x.025']
  results['IG50.CI.upper'] = ICx_est[5,'x.975']
  results['maxEfficacy'] = (1-min(getYcurve(res))) #get the maximum efficacy of the drug
  results['bottom_asymptote'] = res@pars['bottom']
  results['top_asymptote'] = res@pars['top']
  results['hillSlope'] =  res@pars['scal']

  fittedVals <- data.frame(fittedX = getXcurve(res),
                           fittedY = getYcurve(res))
  results <- cbind(results,fittedVals)
  results
}


tmp_iterator <- function(df){
  tryCatch({
    stats <- get_drugResponse_stats(df$conc, df$normViability, useLog=T)
  },error=function(e){
    print(dim(df))
    print(df$conc)
    print(df$normViability)
    print(unique(df$cellLine))
    print(unique(df$drug))
    print(unique(df$experiment))
    print(e)
    stop('stopped')
  })
}

MGH_normViab <- 'syn2773792'
MGH_normViab <- synGet(MGH_normViab)
MGH_normViab <- read.delim(MGH_normViab@filePath, check.names=F, sep="\t",
header=T,stringsAsFactors = FALSE)
#drop unnecassary cols
drop_cols <- c('plate', 'medianDMSO', 'viability')
MGH_normViab <- MGH_normViab[, !colnames(MGH_normViab) %in% drop_cols]

# Drug response
doseResp <- ddply(.data=MGH_normViab, .variables = c('drug', 'cellLine', 'experiment'),
                  .fun = tmp_iterator, .parallel = T)

doseResp_r <- ddply(.data=MGH_normViab, .variables = c('drug', 'cellLine','experiment','replicate'),
                    .fun = tmp_iterator, .parallel = T)

doseResp_new <- ddply(.data=MGH_normViab, .variables = c('drug', 'cellLine'),
                      .fun = tmp_iterator, .parallel = T)

doseResp_r$IC50_nM <- (doseResp_r$IC50)*1000000000

drugs <- c("CUDC907","Panobinostat","GSK2126458")
drugs2 <- c("AR42","Axitinib","AZD2014","Bortezomib","Ganetespib","GDC0941","GDC0980","Vorinostat")

###########

myColors <- c("#384DEA", "#C6A40B", "#BF2B2B")
names(myColors) <- c("AC-CRISPR", "BenMen", "Primary")
colScale <- scale_color_manual(name = "grp",values = myColors)

group <- as.data.frame(cbind(c(rep("AC-CRISPR", 5),"BenMen",rep("Primary",3)), c("Syn1", "Syn2", "Syn3", "Syn4", "Syn5", "Syn6", "Syn7", "Syn10", "Syn12"))) 

names(group) <- c('Cell.Type','cellLine')

MGH_normViab <- full_join(MGH_normViab, group)

doseResp <-full_join(doseResp, group)

doseResp_r <-full_join(doseResp_r, group)

doseResp_new <-full_join(doseResp_new, group)

```

##Dose response curves

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.align="center", fig.width=9, fig.height=4}
SYN_normViab <- MGH_normViab[MGH_normViab$cellLine %in% c("Syn1", "Syn2", "Syn3", "Syn4", "Syn5", "Syn6", "Syn7", "Syn10", "Syn12") & MGH_normViab$drug %in% drugs,]

SYN_doseResp <- doseResp[doseResp$cellLine %in% c("Syn1", "Syn2", "Syn3", "Syn4", "Syn5", "Syn6", "Syn7", "Syn10", "Syn12") & doseResp$drug %in% drugs,]
SYN_doseResp <- SYN_doseResp[order(SYN_doseResp$IC50),]

labelVal <- as.integer(c(min(log10(SYN_normViab$conc*(1e+6))), median(log10(SYN_normViab$conc*(1e+6))), max(log10(SYN_normViab$conc*(1e+6)))))

p1 <- ggplot(SYN_normViab, aes(x = log10(conc*(1e+6)), y = normViability*100))
p1 <- p1 + geom_point(aes(color=Cell.Type), size = 0.1)
p1 <- p1 + geom_line(data = SYN_doseResp, aes(x = fittedX+6, y = fittedY*100, colour = Cell.Type, group = cellLine))
p1 <- p1 + facet_grid(. ~ factor(drug, levels = c("CUDC907","Panobinostat","GSK2126458"))) + theme_bw(base_size = 15)
p1 <- p1 + geom_hline(aes(yintercept=50), color='grey50', linetype='dashed')
p1 <- p1 + xlab(expression(paste('concentration (log10[',mu,'M])', sep = ""))) + ylab('cell viability %')
p1 <- p1 + coord_cartesian(ylim = c(0, 125))
p1 <- p1 + guides(color=guide_legend(title="Cell Type"))
p1 <- p1 + colScale
p1
ggsave(filename = "SYN_drug_response_2Dplot.pdf",width = 9, height = 4)
```

```{r, eval=FALSE, fig.align="center", fig.height=4, fig.width=8, message=FALSE, warning=FALSE, include=FALSE}
SYN_doseResp_r <- doseResp_r[doseResp_r$cellLine %in% c("Syn1", "Syn2", "Syn3", "Syn4", "Syn5", "Syn6", "Syn7", "Syn10", "Syn12") & doseResp_r$drug %in% drugs,]
SYN_doseResp_r <- SYN_doseResp_r[order(SYN_doseResp_r$IC50),]
SYN_doseResp_r$grp <-
paste(SYN_doseResp_r$cellLine,SYN_doseResp_r$replicate)
```

##Primary response table (max response based on 10 micromolar max [drug])

```{r, echo=FALSE, message=FALSE, warning=FALSE, results="asis"}
SYN_doseResp$IC50_nM <- SYN_doseResp$IC50*1000000000
SYN_doseResp$IG50.CI.lower <- SYN_doseResp$IG50.CI.lower*1000000000
SYN_doseResp$IG50.CI.upper <- SYN_doseResp$IG50.CI.upper*1000000000
SYN_doseResp$maxEfficacy100 <- SYN_doseResp$maxEfficacy*100


foo<-distinct(filter(dplyr::select(SYN_doseResp, drug, cellLine, IC50_nM,
maxEfficacy100, IG50.CI.lower, IG50.CI.upper), drug %in% c("CUDC907",
"Panobinostat", "GSK2126458") & cellLine %in% c("Syn1", "Syn2", "Syn3",
"Syn4", "Syn5", "Syn6", "Syn7", "Syn10", "Syn12")))
colnames(foo)<-c("Drug", "Cell Line", "IG50 (nM)", "Max Resp (\\%)",
"IG50.CI.lower", "IG50.CI.upper")

foo$`Cell Line` <- factor(foo$`Cell Line`, levels = c("Syn1", "Syn2",
"Syn3", "Syn4", "Syn5", "Syn6", "Syn7", "Syn10", "Syn12"))
foo$Drug <- factor(foo$Drug, levels = c("CUDC907", "Panobinostat", "GSK2126458"))

foo$`IG50 (nM)`<-round(signif(foo$`IG50 (nM)`,3),1)
foo$`Max Resp (\\%)` <- round(signif(foo$`Max Resp (\\%)`, 3),2)

##nplr returns asymptote if IC50 is out of range, set as not determined for more accuracy
foo$`IG50 (95\\% CI, nM)` <- paste(foo$`IG50 (nM)`, " (",
signif(foo$IG50.CI.lower, 3), " - ", signif(foo$IG50.CI.upper, 3), ")", sep = "")
foo$`IG50 (95\\% CI, nM)`[foo$`IG50 (nM)`>5000] <- ">5000"
foo$`IG50 (95\\% CI, nM)`[foo$`Max Resp (\\%)`<50] <- "n.d."
foo$`IG50 (95\\% CI, nM)`[is.na(foo$`IG50 (nM)`)] <- "n.d."

latex(tabular((`Cell Line` = factor(`Cell Line`)) ~ Heading() * (factor(Drug)) * Heading() * identity * (`IG50 (95\\% CI, nM)` + `Max Resp (\\%)`), data = foo %>% filter(Drug %in% c("CUDC907", "Panobinostat", "GSK2126458"))))
```
#Supplemental Data
##Supplemental Response table

```{r, echo=FALSE, message=FALSE, warning=FALSE, results="asis", resize.width = 8}

SYN_normViab2 <- MGH_normViab[MGH_normViab$cellLine %in% c("Syn1", "Syn2",
"Syn3", "Syn4", "Syn5", "Syn6", "Syn7", "Syn10", "Syn12") & MGH_normViab$drug %in% drugs2,]

SYN_doseResp2 <- doseResp[doseResp$cellLine %in% c("Syn1", "Syn2", "Syn3",
"Syn4", "Syn5", "Syn6", "Syn7", "Syn10", "Syn12") & doseResp$drug %in% drugs2,]
SYN_doseResp2 <- SYN_doseResp2[order(SYN_doseResp2$IC50),]

SYN_doseResp2$IC50_nM <- SYN_doseResp2$IC50*1000000000
SYN_doseResp2$maxEfficacy100 <- SYN_doseResp2$maxEfficacy*100

foo<-distinct(filter(dplyr::select(SYN_doseResp2, drug, cellLine, IC50_nM, maxEfficacy100), drug %in% drugs2 & cellLine %in% c("Syn1", "Syn2", "Syn3", "Syn4", "Syn5", "Syn6", "Syn7", "Syn10", "Syn12")))
colnames(foo)<-c("Drug", "Cell Line", "IG50 (nM)", "Max Response (\\%)")

foo$`Cell Line` <- factor(foo$`Cell Line`, levels = c("Syn1", "Syn2", "Syn3", "Syn4", "Syn5", "Syn6", "Syn7", "Syn10", "Syn12"))


foo$`IG50 (nM)`<-round(signif(foo$`IG50 (nM)`,3),1)
foo$`Max Response (\\%)` <- round(signif(foo$`Max Response (\\%)`, 3),1)

##nplr returns asymptote if IC50 is out of range, set as not determined for more accuracy
foo$`IG50 (nM)`[foo$`IG50 (nM)`>5000] <- ">5000"
foo$`IG50 (nM)`[foo$`Max Response (\\%)`<50] <- "n.d."
foo$`IG50 (nM)`[is.na(foo$`IG50 (nM)`)] <- "n.d."
foo$`IG50 (nM)`[is.na(foo$`IG50 (nM)`)] <- "n.d."

latex(tabular((`Cell Line` = factor(`Cell Line`)) ~ Format(digits = 3) * Heading() * (factor(Drug)) * Heading() * identity * (`IG50 (nM)` +  `Max Response (\\%)`), data = foo %>% filter(Drug %in% c("AR42", "Axitinib", "AZD2014"))))
```
######
```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
latex(tabular((`Cell Line` = factor(`Cell Line`)) ~ Format(digits = 3) * Heading() * (factor(Drug)) * Heading() * identity * (`IG50 (nM)` +  `Max Response (\\%)`), data = foo %>% filter(Drug %in% c("Bortezomib","Ganetespib","GDC0941"))))
```
######
```{r, echo=FALSE, message=FALSE, warning=FALSE, results="asis"}
latex(tabular((`Cell Line` = factor(`Cell Line`)) ~ Format(digits = 3) * Heading() * (factor(Drug)) * Heading() * identity * (`IG50 (nM)` +  `Max Response (\\%)`), data = foo %>% filter(Drug %in% c("GDC0980", "Vorinostat"))))
```

##All other dose response curves

```{r, echo=FALSE, fig.align="center", fig.height=6, fig.width=8, message=FALSE, warning=FALSE}
comp_1_normViab <- MGH_normViab[MGH_normViab$cellLine %in% c("Syn1", "Syn2", "Syn3", "Syn4", "Syn5", "Syn6", "Syn7", "Syn10", "Syn12")  & MGH_normViab$drug %in% drugs2,]
comp_1_drugResp <- doseResp[doseResp$cellLine %in% c("Syn1", "Syn2", "Syn3", "Syn4", "Syn5", "Syn6", "Syn7", "Syn10", "Syn12") & doseResp$drug %in% drugs2,]

p5 <- ggplot(comp_1_normViab, aes(x = log10(conc*(1e+6)), y = normViability*100))
p5 <- p5 + geom_point(aes(color=Cell.Type), size = 0.1)
p5 <- p5 + scale_color_brewer(type = "qual", palette = 2, direction = 1)
p5 <- p5 + geom_line(data = comp_1_drugResp, aes(x = fittedX+6, y = fittedY*100,  colour = Cell.Type, group = cellLine))
p5 <- p5 + facet_wrap(~ drug, ncol = 4) + theme_bw(base_size = 14) + theme(legend.position=c(0.9,0.2))
p5 <- p5 + geom_hline(aes(yintercept=50), color='grey50', linetype='dashed')
p5 <- p5 + xlab(expression(paste('concentration (log10[',mu,'M])', sep = ""))) + ylab('cell viability %')
p5 <- p5 + coord_cartesian(ylim = c(0, 125))
p5 <- p5 + guides(color=guide_legend(title="Cell Type"))
p5 <- p5 + theme(legend.position = "bottom")
p5 <- p5 + colScale
p5

ggsave(filename = "SYN_compare1_drug_response_2Dplot.pdf",width = 10, height = 8)
```
