---
output:
  pdf_document: default
  html_document: default
---
##note that this is incomplete - pca did not work well with these data
```{r, include=FALSE}
library(data.table)
library(plyr)
library(dplyr)
library(synapseClient)
library(ggplot2)
library(tibble)
library(parallel)
synapseLogin()

exp <-fread(synGet("syn9706056")@filePath, sep = "\t", header = TRUE)
exp$gene_id <- exp$V1
exp <- select(exp, -V1)

rsem <- c("Syn5.1" = "syn5269658", "Syn5.2" = "syn5567353", "Syn6" = "syn5269682", 
          "Syn6.DMSO.1" = "syn5567558", "HS01.1" = "syn5567197", "HS01.2" = "syn5567201",
          "HS11.1" = "syn5567229", "HS11.2" = "syn5567233")
```


```{r}
synodos<-lapply(rsem, function(i){
  x <- synGet(i)
  y <- read.table(x@filePath, header = TRUE)
  z <- y %>% select(gene_id, TPM)
  colnames(z) <- c("gene_id", sub(".txt.genes", "", x@annotations@annotations@stringAnnotations$specimenID))
  return(z)
  })

synodos.all <- synodos %>% Reduce(function(dtf1,dtf2)
  full_join(dtf1,dtf2,by="gene_id"), .)
colnames(synodos.all) <- gsub("\\-", "\\.", colnames(synodos.all))

all <- inner_join(synodos.all, exp)
rownames(all) <- all$gene_id
all <- select(all, -gene_id)
all.t <- as.data.frame(t(all))

doPCA <- function(data, colorBy=F, scale=F, center=F, ...){
  #the method requires the data is ordered by row.
  pca_res <- prcomp(data, center=center, scale=scale)
  df = data.frame(pca_res$x[,c(1:3)])
  df$sampleID <- rownames(df)
  percent_variation <- pca_res$sdev^2/sum(pca_res$sdev^2) * 100
  if(colorBy != F){
    temp = data.frame(sampleID = names(colorBy), colorBy = colorBy)
    df <- merge(df,temp, by="sampleID")
    p <- ggplot(data=df, aes(x=PC1,y=PC2, color=colorBy)) 
  } else {
    p <- ggplot(data=df, aes(x=PC1,y=PC2)) 
  }
  p <- p + geom_point() + theme_bw(base_size = 14)
  p + xlab(paste0('PC1 - (', round(percent_variation[1],2), '%)' )) + ylab(paste0('PC2 - ( ', round(percent_variation[2],2), '%)' ))
}
```


```{r, include=FALSE}
##get colors
tss <- read.table(synGet("syn9716995")@filePath, header = TRUE, sep = "\t", comment.char = "", quote = "")
abr <- read.table(synGet("syn9717178")@filePath, header = TRUE, sep = "\t", comment.char = "", quote = "")
abr <- full_join(tss, abr)
samples <- distinct(as.data.frame(colnames(all)))
samples$TSS.Code <- substring(samples$`colnames(all)`, 6, 7)
samples <- full_join(samples, abr)
samples <- select(samples, `colnames(all)`, Study.Abbreviation)
colnames(samples) <- c("sample", "cancer")
samples$cancer[1] <- NA

##thanks jaeddy for the colors
tcga_colors <- tribble(
    ~Color, ~cancer,
    "#ED2891", "BRCA",
    "#B2509E", "GBM",
    "#D49DC7", "LGG",
    "#C1A72F", "ACC",
    "#E8C51D", "PCPG",
    "#F9ED32", "THCA",
    "#104A7F", "CHOL",
    "#9EDDF9", "COAD",
    "#007EB5", "ESCA",
    "#CACCDB", "LIHC",
    "#6E7BA2", "PAAD",
    "#DAF1FC", "READ",
    "#00AEEF", "STAD",
    "#F6B667", "CESC",
    "#D97D25", "OV",
    "#FBE3C7", "UCEC",
    "#F89420", "UCS",
    "#97D1A9", "HNSC",
    "#009444", "UVM",
    "#754C29", "LAML",
    "#CEAC8F", "THYM",
    "#3953A4", "DLBC",
    "#BBD642", "SKCM",
    "#00A99D", "SARC",
    "#D3C3E0", "LUAD",
    "#A084BD", "LUSC",
    "#542C88", "MESO",
    "#FAD2D9", "BLCA",
    "#ED1C24", "KICH",
    "#F8AFB3", "KIRC",
    "#EA7075", "KIRP",
    "#7E1918", "PRAD",
    "#BE1E2D", "TGCT"
)

tcga_colors <- inner_join(samples, tcga_colors) %>% filter(!is.na(sample))
colorBy <- tcga_colors 
names <- colorBy$sample
colorBy <- select(colorBy, Color)
colorBy <- colorBy$Color
names(colorBy) <- names
```
##pca with no threshold
```{r}

pca_res<-prcomp(all)

  df = data.frame(pca_res$x[,c(1:3)])
  df$sampleID <- rownames(all)

  df <- left_join(df, tcga_colors)
  colors <- distinct(select(cors3, Color, cancer))
  colors2 <- colors$Color
  names(colors2) <- colors$cancer
  
  percent_variation <- pca_res$sdev^2/sum(pca_res$sdev^2) * 100
  p <- ggplot(data=df, aes(x=PC1,y=PC2)) 
  p <- p + geom_point() + theme_bw(base_size = 14) + scale_color_manual(colors2) 
  p + xlab(paste0('PC1 - (', round(percent_variation[1],2), '%)' )) +   ylab(paste0('PC2 - ( ', round(percent_variation[2],2), '%)' ))

  plot(p)
  
```

##pca with 5%/95% percentile samples rm
```{r}
all.t$sums <- rowSums(all.t)
hi <- quantile(all.t$sums, 0.95)
lo <- quantile(all.t$sums, 0.05)
all.mini <- filter(all.t, sums<=hi) %>% filter(sums>=lo) %>% select(-sums)

pca_res<-prcomp(all.mini)

  df = data.frame(pca_res$x[,c(1:3)])
  df$sampleID <- rownames(all.mini)

  df <- left_join(df, tcga_colors)
  colors <- distinct(select(cors3, Color, cancer))
  colors2 <- colors$Color
  names(colors2) <- colors$cancer
  
  percent_variation <- pca_res$sdev^2/sum(pca_res$sdev^2) * 100
  p <- ggplot(data=df, aes(x=PC1,y=PC2, color = cancer)) 
  p <- p + geom_point() + theme_bw(base_size = 14) + scale_color_manual(colors2) 
  p + xlab(paste0('PC1 - (', round(percent_variation[1],2), '%)' )) +   ylab(paste0('PC2 - ( ', round(percent_variation[2],2), '%)' ))

  plot(p)
  
```
##pca with 10%/90% percentile rm
```{r}
all.t$sums <- rowSums(all.t)
hi <- quantile(all.t$sums, 0.9)
lo <- quantile(all.t$sums, 0.1)
all.ex.mini <- filter(all.t, sums<=hi) %>% filter(sums>=lo) %>% select(-sums)

pca_res<-prcomp(all.ex.mini)

  df = data.frame(pca_res$x[,c(1:3)])
  df$sampleID <- rownames(all.ex.mini)

  df <- left_join(df, tcga_colors)
  colors <- distinct(select(cors3, Color, cancer))
  colors2 <- colors$Color
  names(colors2) <- colors$cancer
  
  percent_variation <- pca_res$sdev^2/sum(pca_res$sdev^2) * 100
  p <- ggplot(data=df, aes(x=PC1,y=PC2)) 
  p <- p + geom_point() + theme_bw(base_size = 14) + scale_color_manual(colors2) 
  p + xlab(paste0('PC1 - (', round(percent_variation[1],2), '%)' )) +   ylab(paste0('PC2 - ( ', round(percent_variation[2],2), '%)' ))

  plot(p)

```


