---
output:
  pdf_document: 
    fig_height: 6
    fig_width: 8
  html_document: default
---

```{r, message=FALSE, warning=FALSE, include=FALSE}
library(data.table)
library(plyr)
library(dplyr)
library(synapseClient)
library(ggplot2)
library(tibble)
library(parallel)
library(Rtsne.multicore)

synapseLogin()

exp <-fread(synGet("syn9706056")@filePath, sep = "\t", header = TRUE)
exp$gene_id <- exp$V1
exp <- select(exp, -V1)

rsem <- tibble::tribble(
         ~synid,          ~sample,
   "syn5269690",       "MIN31981",
   "syn5269698",         "MN408a",
   "syn5269706",         "MN408b",
   "syn5269714",         "MN408c",
   "syn5269722",    "MN460_MN556",
   "syn5269731",          "MN466",
   "syn5269739",          "MN479",
   "syn5269747",          "MN491",
   "syn5269755",          "MN492",
   "syn5269762",          "MN505",
   "syn5269771",          "MN506",
   "syn5269779",          "MN514",
   "syn5269787",          "MN516",
   "syn5269795",          "MN520",
   "syn5269803",          "MN521",
   "syn5269810",          "MN527",
   "syn5269819",          "MN529",
   "syn5269827",          "MN533",
   "syn5269835",          "MN548",
   "syn5269843",          "MN560",
   "syn5269850",          "MN563",
   "syn5269858",          "MN567",
   "syn5269866",          "MN571",
   "syn5269874",          "MN572",
   "syn5269881",  "NFT_735_MN522",
   "syn5269889",  "xT_6491_MN474",
   "syn5567261",        "MN491-1",
   "syn5567265",        "MN491-2",
   "syn5567269",        "MN527-1",
   "syn5567273",        "MN527-2",
   "syn5567277",        "MN571-1",
   "syn5567281",        "MN571-2"
  )

rsem2 <- (c("Syn.DMSO.1" = "syn5567534", "Syn1.DMSO.2" = "syn5567538","Syn5.1" = "syn5269658", "Syn5.2" = "syn5567353", "Syn6" = "syn5269682", 
          "Syn6.DMSO.1" = "syn5567558", "HS01.1" = "syn5567197", "HS01.2" = "syn5567201",
          "HS11.1" = "syn5567229", "HS11.2" = "syn5567233"))

```


```{r, message=FALSE, warning=FALSE, include=FALSE}
synodos<-mclapply(rsem$synid, function(i){
  x <- synGet(i)
  y <- read.table(x@filePath, header = TRUE)
  z <- y %>% select(gene_id, TPM)
  colnames(z) <- c("gene_id", sub(".txt.genes", "", x@annotations@annotations@stringAnnotations$specimenID))
  return(z)
  }, mc.cores = detectCores())

synodos.mn <- synodos %>% Reduce(function(dtf1,dtf2)
  full_join(dtf1,dtf2,by="gene_id"), .)
colnames(synodos.mn) <- gsub("\\-", "\\.", colnames(synodos.mn))

synodos2<-mclapply(rsem2, function(i){
  x <- synGet(i)
  y <- read.table(x@filePath, header = TRUE)
  z <- y %>% select(gene_id, TPM)
  colnames(z) <- c("gene_id", sub(".txt.genes", "", x@annotations@annotations@stringAnnotations$specimenID))
  return(z)
  }, mc.cores = detectCores())

synodos.cell <- synodos2 %>% Reduce(function(dtf1,dtf2)
  full_join(dtf1,dtf2,by="gene_id"), .)
colnames(synodos.cell) <- gsub("\\-", "\\.", colnames(synodos.cell))

synodos.all <- inner_join(synodos.mn, synodos.cell)

all <- inner_join(synodos.all, exp)
rownames(all) <- all$gene_id
all <- select(all, -gene_id)
```


```{r, message=FALSE, warning=FALSE, include=FALSE}
##get colors
tss <- read.table(synGet("syn9716995")@filePath, header = TRUE, sep = "\t", comment.char = "", quote = "")
abr <- read.table(synGet("syn9717178")@filePath, header = TRUE, sep = "\t", comment.char = "", quote = "")
abr <- full_join(tss, abr)
samples <- distinct(as.data.frame(colnames(all)))
samples$TSS.Code <- substring(samples$`colnames(all)`, 6, 7)
samples <- full_join(samples, abr)
samples <- select(samples, `colnames(all)`, Study.Abbreviation)
colnames(samples) <- c("sample", "cancer")

##thanks jaeddy for the colors
tcga_colors <- tribble(
    ~Color, ~cancer,
    "#ED2891", "BRCA",
    "#B2509E", "GBM",
    "#D49DC7", "LGG",
    "#C1A72F", "ACC",
    "#E8C51D", "PCPG",
    "#F9ED32", "THCA",
    "#104A7F", "CHOL",
    "#9EDDF9", "COAD",
    "#007EB5", "ESCA",
    "#CACCDB", "LIHC",
    "#6E7BA2", "PAAD",
    "#DAF1FC", "READ",
    "#00AEEF", "STAD",
    "#F6B667", "CESC",
    "#D97D25", "OV",
    "#FBE3C7", "UCEC",
    "#F89420", "UCS",
    "#97D1A9", "HNSC",
    "#009444", "UVM",
    "#754C29", "LAML",
    "#CEAC8F", "THYM",
    "#3953A4", "DLBC",
    "#BBD642", "SKCM",
    "#00A99D", "SARC",
    "#D3C3E0", "LUAD",
    "#A084BD", "LUSC",
    "#542C88", "MESO",
    "#FAD2D9", "BLCA",
    "#ED1C24", "KICH",
    "#F8AFB3", "KIRC",
    "#EA7075", "KIRP",
    "#7E1918", "PRAD",
    "#BE1E2D", "TGCT"
)

tcga_colors <- inner_join(samples, tcga_colors) %>% filter(!is.na(sample))
colorBy <- tcga_colors 
names <- colorBy$sample
colorBy <- select(colorBy, Color)
colorBy <- colorBy$Color
names(colorBy) <- names
```
##t-SNE colored by cancer
```{r, echo=FALSE, message=FALSE, warning=FALSE}
all.t <- as.data.frame(t(all))
set.seed(30)
tsne_out <- Rtsne.multicore(all.t)

df <- as.data.frame(tsne_out$Y)
df$sample <- rownames(all.t)
df <- left_join(df, tcga_colors)
df$cancer[1:42] <- "Synodos"
df$Color[1:42] <- "#000000"
colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer)) + 
     geom_point() + 
     scale_color_manual(values=colors2) 

plot(p)
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}

colors3<-colors
colors3$Color[colors3$cancer!="Synodos"] <- "#000000"
colors3$Color[colors3$cancer!="Synodos"] <- "#BBD642"
colors4 <- colors3$Color
names(colors4) <- colors3$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer)) + 
     geom_point() + 
     scale_color_manual(values=colors4) +
     geom_point(data = subset(df, cancer = "Synodos")) 

plot(p)
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
p <- ggplot(data=df %>% filter(cancer == "Synodos"), aes(x=V1,y=V2, color = cancer)) + 
     geom_point() +
     scale_color_manual(values=colors4)

plot(p)
```

##tpm expression data, tsne, perplexity 2,5,30,50,1000 top to bottom
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}

set.seed(30)
tsne_out <- Rtsne.multicore(all.t,  perplexity = 2)
tsne_out1 <- Rtsne.multicore(all.t, perplexity = 5)
tsne_out2 <- Rtsne.multicore(all.t, perplexity = 30)
tsne_out3 <- Rtsne.multicore(all.t, perplexity = 50)
tsne_out4 <- Rtsne.multicore(all.t, perplexity = 1000)

df <- as.data.frame(tsne_out$Y)
df$sample <- rownames(all.t)
df <- left_join(df, tcga_colors)
df$cancer[1:42] <- "Synodos"
df$Color[1:42] <- "#000000"
colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer, alpha = 0.25)) + 
     geom_point() + 
     scale_color_manual(values=colors2) 

plot(p)

df <- as.data.frame(tsne_out1$Y)
df$sample <- rownames(all.t)
df <- left_join(df, tcga_colors)
df$cancer[1:42] <- "Synodos"
df$Color[1:42] <- "#000000"

colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer, alpha = 0.25)) + 
     geom_point() + 
     scale_color_manual(values=colors2) 

plot(p)

df <- as.data.frame(tsne_out2$Y)
df$sample <- rownames(all.t)
df <- left_join(df, tcga_colors)
df$cancer[1:42] <- "Synodos"
df$Color[1:42] <- "#000000"
colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer, alpha = 0.25)) + 
     geom_point() + 
     scale_color_manual(values=colors2) 

plot(p)

df <- as.data.frame(tsne_out3$Y)
df$sample <- rownames(all.t)
df <- left_join(df, tcga_colors)
df$cancer[1:40] <- "Synodos"
df$Color[1:40] <- "#000000"
colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer, alpha = 0.25)) + 
     geom_point() + 
     scale_color_manual(values=colors2) 

plot(p)

df <- as.data.frame(tsne_out4$Y)
df$sample <- rownames(all.t)
df <- left_join(df, tcga_colors)
df$cancer[1:42] <- "Synodos"
df$Color[1:42] <- "#000000"
colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer, alpha = 0.25)) + 
     geom_point() + 
     scale_color_manual(values=colors2) 

plot(p)
```

##rank based expression data, tsne, perplexity 2,5,30,50,1000 top to bottom
```{r, echo=FALSE, message=FALSE, warning=FALSE}

all.rank <- mclapply(colnames(all.t), function(p) rank(all.t[,p]), mc.cores = detectCores())

all.rank <- as.data.frame(t(ldply(all.rank)))
colnames(all.rank) <- colnames(all.t)
rownames(all.rank) <- rownames(all.t)

set.seed(30)
tsne_out <- Rtsne.multicore(all.rank,  perplexity = 2)
tsne_out1 <- Rtsne.multicore(all.rank, perplexity = 5)
tsne_out2 <- Rtsne.multicore(all.rank, perplexity = 30)
tsne_out3 <- Rtsne.multicore(all.rank, perplexity = 50)
tsne_out4 <- Rtsne.multicore(all.rank, perplexity = 1000)

df <- as.data.frame(tsne_out$Y)
df$sample <- rownames(all.t)
df <- left_join(df, tcga_colors)
df$cancer[1:42] <- "Synodos"
df$Color[1:42] <- "#000000"
colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer, alpha = 0.25)) + 
     geom_point() + 
     scale_color_manual(values=colors2) 

plot(p)

df <- as.data.frame(tsne_out1$Y)
df$sample <- rownames(all.t)
df <- left_join(df, tcga_colors)
df$cancer[1:42] <- "Synodos"
df$Color[1:42] <- "#000000"

colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer, alpha = 0.25)) + 
     geom_point() + 
     scale_color_manual(values=colors2) 

plot(p)

df <- as.data.frame(tsne_out2$Y)
df$sample <- rownames(all.t)
df <- left_join(df, tcga_colors)
df$cancer[1:42] <- "Synodos"
df$Color[1:42] <- "#000000"
colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer, alpha = 0.25)) + 
     geom_point() + 
     scale_color_manual(values=colors2) 

plot(p)

df <- as.data.frame(tsne_out3$Y)
df$sample <- rownames(all.t)
df <- left_join(df, tcga_colors)
df$cancer[1:40] <- "Synodos"
df$Color[1:40] <- "#000000"
colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer, alpha = 0.25)) + 
     geom_point() + 
     scale_color_manual(values=colors2) 

plot(p)

df <- as.data.frame(tsne_out4$Y)
df$sample <- rownames(all.t)
df <- left_join(df, tcga_colors)
df$cancer[1:42] <- "Synodos"
df$Color[1:42] <- "#000000"
colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer, alpha = 0.25)) + 
     geom_point() + 
     scale_color_manual(values=colors2) 

plot(p)
```

##perplexity=3
```{r, echo=FALSE, message=FALSE, warning=FALSE}
syns <- colnames(synodos.all[,-1])
syn <- select(all, one_of(syns))
syn.t <- t(syn)

set.seed(30)

tsne_out_syn_3 <- Rtsne.multicore(syn.t, perplexity = 3)

df <- as.data.frame(tsne_out_syn_3$Y)
df$sample <- rownames(syn.t)
df <- left_join(df, tcga_colors)
df$cancer[1:32] <- "MN_Tumor"
df$Color[1:32] <- "red"
df$cancer[33:38] <- "MN_Cell"
df$Color[33:38] <- "blue"
df$cancer[39:42] <- "SCH_Cell"
df$Color[39:42] <- "darkgreen"
colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer)) + 
     geom_point() + 
     geom_text(aes(label=sample), size = 3, nudge_y = 1) +
     scale_color_manual(values=colors2) 

plot(p)
```

##perplexity=9

```{r, echo=FALSE, message=FALSE, warning=FALSE}
tsne_out_syn_9 <- Rtsne.multicore(syn.t, perplexity = 9)

df <- as.data.frame(tsne_out_syn_9$Y)
df$sample <- rownames(syn.t)
df <- left_join(df, tcga_colors)
df$cancer[1:32] <- "MN_Tumor"
df$Color[1:32] <- "red"
df$cancer[33:38] <- "MN_Cell"
df$Color[33:38] <- "blue"
df$cancer[39:42] <- "SCH_Cell"
df$Color[39:42] <- "darkgreen"
colors <- distinct(select(df, cancer, Color))
colors2 <- colors$Color
names(colors2) <- colors$cancer

p <- ggplot(data=df, aes(x=V1,y=V2, color = cancer)) + 
     geom_point() + 
     geom_text(aes(label=sample), size = 3, nudge_y = 1) +
     scale_color_manual(values=colors2) 

plot(p)
```